### ISSUE TITLE
Open valid API keys

### ISSUE THREAD

**Issue by starkodder** [OS2web/os2web8#176]
There are valid API keys for [the speedadmin API](https://api.speedadmin.dk/) in 2 places in this repository: 
[https://github.com/OS2web/os2web8/blob/7506f413228164bb297e35bac1b5eaf9121be4d8/web/modules/custom/bc_speed_admin/src/Controller/Request.php#L6](https://github.com/OS2web/os2web8/blob/7506f413228164bb297e35bac1b5eaf9121be4d8/web/modules/custom/bc_speed_admin/src/Controller/Request.php#L6) and[https://github.com/OS2web/os2web8/blob/7506f413228164bb297e35bac1b5eaf9121be4d8/web/modules/custom/bc_speed_admin/src/Controller/Image.php#L6](https://github.com/OS2web/os2web8/blob/7506f413228164bb297e35bac1b5eaf9121be4d8/web/modules/custom/bc_speed_admin/src/Controller/Image.php#L6), please remove them.

**Comment by skifter** [comment]
Hi

Sorry about that. We will get it fixed.

**Comment by skifter** [comment]
It should have been removed. Let me know if there are other problems.
